"""Regenerate docs/Master_Index.md from docs/notes/ frontmatter + _bmad-output/ artifacts.

Manual/periodic utility (not a Gate, not wired into dev.bat or CI). Run after adding or
editing vault notes:

    python scripts/_reindex_vault.py
"""
import re
from pathlib import Path

import yaml

FRONTMATTER_RE = re.compile(r"^---\n(.*?)\n---\n?", re.DOTALL)
REQUIRED_FIELDS = ["type", "date", "status"]
TYPE_ORDER = ["research", "decision", "evidence", "reference"]

# Repo-relative paths of the stable core docs, linked from a "Start here" section so a
# fresh session (or the Obsidian graph) can navigate from Master_Index.md to everything
# else without scanning the repo. Missing paths are skipped with a warning.
CORE_DOCS = [
    ("CLAUDE.md", "Project guide (auto-loaded): model tiers, Gates A-D table, workflow + deploy rules"),
    ("architecture_spec.md", "Canonical architecture spec"),
    ("RUNS.md", "Run log, newest entry first — source of truth for run history + the guardrail/REVERT rule"),
    ("README.md", "Repo overview"),
    ("docs/superpowers/specs/2026-07-01-obsidian-vault-design.md", "This vault's design spec"),
]

# Repo-root working docs linked under "Working docs & plans" alongside a glob of
# docs/superpowers/plans/*.md, so they show as connected in the Obsidian graph.
ROOT_WORKING_DOCS = [
    ("audit_checkpoint.md", "2026-07-08 audit: ranked latent-bug findings + per-item status"),
    ("remediation_plan.md", "Audit remediation plan (executed 2026-07-09/10, see RUNS.md)"),
]

_DEFAULTS = {
    "type": "unknown",
    "date": "",
    "status": "unknown",
    "model_version": "n/a",
    "related_code_files": [],
    "related_runs_entry": "",
    "tags": [],
}


def parse_note(path: Path, repo_root: Path) -> dict:
    def _copy_lists(d):
        """Copy list values in dict to avoid shared mutable state."""
        return {k: v.copy() if isinstance(v, list) else v for k, v in d.items()}

    text = path.read_text(encoding="utf-8")
    rel_path = path.relative_to(repo_root).as_posix()
    match = FRONTMATTER_RE.match(text)
    if not match:
        return {"_path": rel_path, "_warnings": ["no frontmatter found"], **_copy_lists(_DEFAULTS)}

    try:
        data = yaml.safe_load(match.group(1)) or {}
    except yaml.YAMLError:
        return {"_path": rel_path, "_warnings": ["invalid YAML frontmatter"], **_copy_lists(_DEFAULTS)}

    warnings = [f"missing field: {f}" for f in REQUIRED_FIELDS if not data.get(f)]
    result = {"_path": rel_path, "_warnings": warnings}
    for key, default in _DEFAULTS.items():
        value = data.get(key, default)
        if key == "date" and value:
            result[key] = str(value)
        elif value:
            result[key] = value
        else:
            # Use default, copying list values to avoid shared mutable state
            result[key] = default.copy() if isinstance(default, list) else default
    return result


def collect_notes(notes_dir: Path, repo_root: Path) -> list:
    paths = sorted(notes_dir.glob("**/*.md"))
    return [parse_note(p, repo_root) for p in paths]


def collect_bmad_docs(bmad_dir: Path, repo_root: Path) -> list:
    paths = sorted(bmad_dir.glob("**/*.md"))
    return [p.relative_to(repo_root).as_posix() for p in paths]


def build_reverse_index(notes: list) -> dict:
    reverse: dict = {}
    for note in notes:
        for code_path in note.get("related_code_files", []):
            reverse.setdefault(code_path, []).append(note["_path"])
    return {k: sorted(v) for k, v in sorted(reverse.items())}


def _version_sort_key(version_str: str):
    """Sort key for model_version strings: numeric tuple, with 'n/a' always last.

    Examples:
        "v8.2" -> (0, (8, 2))
        "v8.9" -> (0, (8, 9))
        "v8.10" -> (0, (8, 10))
        "v9" -> (0, (9,))
        "n/a" -> (1,)  # Always sorts after all real versions
    """
    if version_str == "n/a":
        return (1,)
    # Extract all digit groups and convert to tuple of ints
    digits = tuple(int(d) for d in re.findall(r'\d+', version_str))
    return (0, digits)


def render_index(notes: list, bmad_docs: list, reverse_index: dict, core_docs: list,
                 working_docs: list) -> str:
    lines = [
        "# Master Index",
        "",
        "Generated by `scripts/_reindex_vault.py` — do not hand-edit.",
        "",
        "## Start here (core repo docs)",
        "",
    ]
    for path, desc in core_docs:
        # Index lives in docs/, so repo-root paths need one level up
        link = path[len("docs/"):] if path.startswith("docs/") else f"../{path}"
        lines.append(f"- [{path}]({link}) — {desc}")
    if working_docs:
        lines += ["", "## Working docs & plans", ""]
        for path, desc in working_docs:
            link = path[len("docs/"):] if path.startswith("docs/") else f"../{path}"
            lines.append(f"- [{path}]({link}) — {desc}")

    lines += [
        "",
        "## Notes by type",
        "",
    ]

    if not notes:
        lines.append("_No notes yet — add markdown files under `docs/notes/`._")
        lines.append("")
    else:
        types_present = sorted(
            {n["type"] for n in notes},
            key=lambda t: (TYPE_ORDER.index(t) if t in TYPE_ORDER else len(TYPE_ORDER), t),
        )
        for t in types_present:
            lines.append(f"### {t}")
            lines.append("")
            group = [n for n in notes if n["type"] == t]
            versions = sorted({n["model_version"] for n in group}, key=_version_sort_key)
            for v in versions:
                lines.append(f"**{v}**")
                lines.append("")
                for n in sorted(group, key=lambda n: n["_path"]):
                    if n["model_version"] != v:
                        continue
                    warn = f" _(warnings: {', '.join(n['_warnings'])})_" if n["_warnings"] else ""
                    lines.append(f"- [{n['_path']}]({n['_path']}){warn}")
                lines.append("")

    lines.append("## Code -> notes (reverse lookup)")
    lines.append("")
    if not reverse_index:
        lines.append("_No notes reference `related_code_files` yet._")
        lines.append("")
    else:
        for code_path, note_paths in reverse_index.items():
            lines.append(f"- `{code_path}`")
            for np_ in note_paths:
                lines.append(f"  - [{np_}]({np_})")
        lines.append("")

    lines.append("## BMAD artifacts (`_bmad-output/`)")
    lines.append("")
    if not bmad_docs:
        lines.append("_No BMAD artifacts found._")
    else:
        for path in bmad_docs:
            lines.append(f"- [{path}]({path})")

    return "\n".join(lines).rstrip() + "\n"


def main() -> None:
    repo_root = Path(__file__).resolve().parents[1]
    notes_dir = repo_root / "docs" / "notes"
    bmad_dir = repo_root / "_bmad-output"
    index_path = repo_root / "docs" / "Master_Index.md"

    notes = collect_notes(notes_dir, repo_root)
    bmad_docs = collect_bmad_docs(bmad_dir, repo_root)
    reverse_index = build_reverse_index(notes)

    core_docs = []
    for path, desc in CORE_DOCS:
        if (repo_root / path).exists():
            core_docs.append((path, desc))
        else:
            print(f"WARNING: core doc missing, skipped: {path}")

    for note in notes:
        for w in note["_warnings"]:
            print(f"WARNING: {note['_path']}: {w}")

    working_docs = []
    for path, desc in ROOT_WORKING_DOCS:
        if (repo_root / path).exists():
            working_docs.append((path, desc))
        else:
            print(f"WARNING: working doc missing, skipped: {path}")
    plans_dir = repo_root / "docs" / "superpowers" / "plans"
    for p in sorted(plans_dir.glob("*.md")) if plans_dir.exists() else []:
        rel = p.relative_to(repo_root).as_posix()
        working_docs.append((rel, "Implementation plan"))

    index_path.write_text(render_index(notes, bmad_docs, reverse_index, core_docs, working_docs), encoding="utf-8")
    print(f"Wrote docs/Master_Index.md ({len(notes)} notes, {len(bmad_docs)} BMAD docs)")


if __name__ == "__main__":
    main()
